apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
       - name: content
         persistentVolumeClaim:
          claimName: pvc1
      containers:
      - image: nginx:latest
        name: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: content
           mountPath: /usr/share/nginx/html
