apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
 labels:
  pv: v1
spec:
 accessModes:
  - ReadWriteMany
 capacity:
  storage: 2Gi
 storageClassName: nfs
 mountOptions:
  - hard
  - nfsvers=4.1
 nfs:
  server: 192.168.126.11
  path: /path
